<?php

/*
 * Purpose: Register css and js scripts from our manifest.json files
 * generated by webpack
 * */


/*
 * Get the entry point for this resource from the assets_manifest_entry tv
 * */
$tv = $modx->getObject('modTemplateVar', array('name' => 'assets_manifest_entry'));
$resid = $modx->resource->id;
if(!$tv->getValue($resid)){
    return;
}else{
    $entry_file = $tv->getValue($resid);
}


$manifest = MODX_ASSETS_PATH . 'dist/manifest.json';
//$entry_file = "handlebars";

if (file_exists($manifest)) {
    $manifest_entry_files = json_decode(file_get_contents($manifest), true);

    /*
     * Ensure we have a valid entry for this resource in our manaifest.json
     * */
    if(is_array($resource_entry_files = $manifest_entry_files["entryPoints"][$entry_file])){

        /*
         * If we have js files regsiter them
         * */
        if (array_key_exists("js", $resource_entry_files)) {
            foreach ($resource_entry_files["js"] as $js_file) {
                $modx->regClientScript("assets/dist/" . $js_file);
            }
        }

        /*
         * If we have css files register them
         * */
        if (array_key_exists("css", $resource_entry_files)) {
            foreach ($resource_entry_files["css"] as $css_file) {
                $modx->regClientCSS("assets/dist/" . $css_file);
            }
        }
    }

    /**/
}